# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            VIDEO DILLERS
tagline:          VIDEO DILLERS
url:              http://videodillers.com

baseurl:          /


site_description: we love video we do video you get profit
text_0: videos
text_1: who we are
text_2: how it works
text_3: contact

text_4: we love video
text_5: we do video
text_6: you get profit

